import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      colors: {
        primary: 'var(--md-primary)',
        'on-primary': 'var(--md-on-primary)',
        'primary-container': 'var(--md-primary-container)',
        'on-primary-container': 'var(--md-on-primary-container)',
        secondary: 'var(--md-secondary)',
        'on-secondary': 'var(--md-on-secondary)',
        'secondary-container': 'var(--md-secondary-container)',
        'on-secondary-container': 'var(--md-on-secondary-container)',
        tertiary: 'var(--md-tertiary)',
        'on-tertiary': 'var(--md-on-tertiary)',
        'tertiary-container': 'var(--md-tertiary-container)',
        'on-tertiary-container': 'var(--md-on-tertiary-container)',
        surface: 'var(--md-surface)',
        'on-surface': 'var(--md-on-surface)',
        'on-surface-variant': 'var(--md-on-surface-variant)',
        'surface-container': 'var(--md-surface-container)',
        'surface-container-low': 'var(--md-surface-container-low)',
        'surface-container-lowest': 'var(--md-surface-container-lowest)',
        'surface-container-high': 'var(--md-surface-container-high)',
        'surface-container-highest': 'var(--md-surface-container-highest)',
        outline: 'var(--md-outline)',
        'outline-variant': 'var(--md-outline-variant)',
        error: 'var(--md-error)',
        'on-error': 'var(--md-on-error)',
        'error-container': 'var(--md-error-container)',
        'on-error-container': 'var(--md-on-error-container)',
        'inverse-surface': 'var(--md-inverse-surface)',
        'inverse-on-surface': 'var(--md-inverse-on-surface)',
        success: 'var(--md-success)',
        'success-container': 'var(--md-success-container)',
        warning: 'var(--md-warning)',
        'warning-container': 'var(--md-warning-container)',
        info: 'var(--md-info)',
        'info-container': 'var(--md-info-container)',
      },
      borderRadius: {
        'm3-sm': '8px',
        'm3': '12px',
        'm3-lg': '16px',
        'm3-xl': '28px',
      },
    },
  },
  plugins: [],
} satisfies Config
